### ISSUE TITLE
Drop down menu for sections

### ISSUE THREAD

**Issue by smortezah** [octokatherine/readme.so#133] opened 2021-05-06 09:21 UTC
It could be great if the sections to be added were listed in a drop down menu, for easier accessibility.

**Comment by MicahBCode** [comment] 2021-05-10 09:49
This is a duplicate of #85 and may be closed.

**Comment by daacode** [comment] 2021-06-04 21:08
Can I work on this?

**Comment by octokatherine** [comment] 2021-08-17 04:10
@daacode yes, do you still want to work on it?

**Comment by daacode** [comment] 2021-08-17 04:16
Hi @octokatherine, definitely I still want to work on it

**Closed** 2021-12-28 19:39 UTC
