### ISSUE TITLE
Some sections disappeared after reset

### ISSUE THREAD

**Issue by theilgazcode** [octokatherine/readme.so#180] opened 2021-07-13 12:04 UTC
I added some sections from available list, then I clicked reset button. Some sections disappeared. 

![added](https://user-images.githubusercontent.com/13048645/125448276-82ff511e-57d5-4489-b91e-0630c76d926f.PNG)

Here is the section list after reset operation:

![21](https://user-images.githubusercontent.com/13048645/125448498-abd670a0-d730-49e0-a0f9-6a79c15f9d35.png)

**Comment by octokatherine** [comment] 2021-07-13 17:08
@theilgazcode this is actually the intended behavior. The reset button returns the page to the default state, with only the "Title and description" section selected.

I'd be curious to hear what you expected to happen, and if there's anything you think we could do to make this more clear

**Comment by theilgazcode** [comment] 2021-07-14 07:28
> @theilgazcode this is actually the intended behavior. The reset button returns the page to the default state, with only the "Title and description" section selected.
> 
> I'd be curious to hear what you expected to happen, and if there's anything you think we could do to make this more clear

I mean Github Profile sections disappeared after reset.

**Comment by jose-vale** [comment] 2021-07-20 09:27
This issue was resolved in #166 but the fix seems to have been reverted in #135.

**Comment by Rishabh-Rathod** [comment] 2021-07-23 17:30
[Here](https://github.com/octokatherine/readme.so/pull/135/files#diff-a74479fa9aac19ae678df956773cfaec28d573c6738429b6f6ddef07bdcbc57dR103-R110) while resolving merge conflicts, I by-mistake reverted the above-mentioned #166 fix. It was unintentional.

**Comment by jose-vale** [comment] 2021-07-24 20:40
> [Here](https://github.com/octokatherine/readme.so/pull/135/files#diff-a74479fa9aac19ae678df956773cfaec28d573c6738429b6f6ddef07bdcbc57dR103-R110) while resolving merge conflicts, I by-mistake reverted the above-mentioned #166 fix. It was unintentional.

No worries, I'll just resubmit the PR.

**Closed** 2021-07-26 18:26 UTC
