### ISSUE TITLE
[FEATURE] Translate to Brazilian Portuguese PT-BR

### ISSUE THREAD

**Issue by TheNeoCarvalho** [octokatherine/readme.so#127] opened 2021-05-04 18:17 UTC
Hi, I would like to translate it into Brazilian Portuguese.

**Comment by waldyrious** [comment] 2021-05-04 18:31
@TheNeoCarvalho there's already work in progress for this — see #72, and the associated PR, #73.

**Comment by waldyrious** [comment] 2021-05-29 11:14
@katherinepeterson this issue is a duplicate of #72, so it can be closed as well.

**Closed** 2021-08-15 19:19 UTC
